export const getDashboardConstants = {
	GET_REQUEST: "GET_DASHBOARD_REQUEST",
	GET_SUCCESS: "GET_DASHBOARD_SUCCESS",
	GET_FAILURE: "GET_DASHBOARD_FAILURE",

	// POST_REQUEST: "SAMPLE_POST_REQUEST",
	// POST_SUCCESS: "SAMPLE_POST_SUCCESS",
	// POST_FAILURE: "SAMPLE_POST_FAILURE",
	
	// PUT_REQUEST: "SAMPLE_PUT_REQUEST",
	// PUT_SUCCESS: "SAMPLE_PUT_SUCCESS",
	// PUT_FAILURE: "SAMPLE_PUT_FAILURE",
	
	// DELETE_REQUEST: "SAMPLE_DELETE_REQUEST",
	// DELETE_SUCCESS: "SAMPLE_DELETE_SUCCESS",
	// DELETE_FAILURE: "SAMPLE_DELETE_FAILURE",

}